ALTER TABLE "SyncDS_User" ADD "DomainId" VARCHAR2(4000) NULL
;
ALTER TABLE "SyncDS_Group" ADD "DomainId" VARCHAR2(4000) NULL
;

CREATE SEQUENCE "SyncDS_LookupTableMetaData_seq"
START WITH     1
INCREMENT BY   1
NOCACHE
NOCYCLE;

CREATE SEQUENCE "SyncDS_UserData_seq"
START WITH     1
INCREMENT BY   1
NOCACHE
NOCYCLE;
